name: auth-cc-jwt
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: Arminmsg/action-test@af1c744850ed39268941e965c606e2da6f806127
        with:
          secrets: db/sqlusername|sql_username;db/sql_password;
      - name: Multiline
        uses: Arminmsg/action-test@af1c744850ed39268941e965c606e2da6f806127
        with:
          secrets: |
            db/sqlusername|sql_username;
            db/sql_password
