name: auth-cc-jwt
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: Arminmsg/action-test@d9da3500eb729e05ddad3e982cbe680f7cc916d0
        with:
          secrets: db/sqlusername|sql_username;db/sql_password;
      - name: Multiline
        uses: Arminmsg/action-test@d9da3500eb729e05ddad3e982cbe680f7cc916d0
        with:
          secrets: |
            db/sqlusername|sql_username;
            db/sql_password
